// Generated browser bundle from jolteondark/mapless-migration-practice main 0029486126aab849e1f9e14e667f24a45dcea1de.
// Sources: web/battle-capture-flow.js, web/party-storage-handoff.js,
// web/caught-queue-party-storage.js, web/bag-economy-mart-flow.js, web/run-persistence.js.

function asInt(value, field) { const n = Number(value); if (!Number.isInteger(n)) throw new TypeError(`${field} must be an integer`); return n; }
function nextRandom(values, limit, cursor) { if (!Array.isArray(values) || cursor.index >= values.length) throw new RangeError("deterministic random input exhausted"); const n = asInt(values[cursor.index++], "random value"); if (n < 0 || n >= limit) throw new RangeError(`random value must be in [0, ${limit})`); return n; }
function dexModifier(ownedCount) { if (ownedCount > 600) return 5; if (ownedCount > 450) return 4; if (ownedCount > 300) return 3; if (ownedCount > 150) return 2; if (ownedCount > 30) return 1; return 0; }
export function calculateCapture(input) {
  const totalHp = asInt(input.totalHp, "totalHp"); const hp = asInt(input.hp, "hp");
  if (totalHp <= 0 || hp < 0 || hp > totalHp) throw new RangeError("invalid HP state");
  if (input.debugCapture) return { numShakes: 4, criticalCapture: false, x: null, y: null, randomUsed: 0 };
  let catchRate = asInt(input.catchRate, "catchRate"); if (catchRate < 0) throw new RangeError("catchRate must be non-negative");
  if (input.ultraBeast && input.ball !== "BEASTBALL") catchRate = Math.floor(catchRate / 10); else if (input.modifiedCatchRate != null) catchRate = asInt(input.modifiedCatchRate, "modifiedCatchRate");
  let x = (((3 * totalHp) - (2 * hp)) * catchRate) / (3 * totalHp); const status = input.status ?? "NONE";
  if (status === "SLEEP" || status === "FROZEN") x *= 2.5; else if (status !== "NONE") x *= 1.5; x = Math.floor(x); if (x < 1) x = 1;
  if (x >= 255 || input.unconditional) return { numShakes: 4, criticalCapture: false, x, y: null, randomUsed: 0 };
  const y = Math.floor(65536 / ((255 / x) ** 0.1875)); const cursor = { index: 0 }; const randomValues = input.randomValues ?? [];
  if (input.enableCriticalCaptures) { let modifier = dexModifier(asInt(input.ownedCount ?? 0, "ownedCount")); if (input.catchingCharm) modifier *= 2; const c = Math.floor((x * modifier) / 12); if (c > 0 && nextRandom(randomValues, 256, cursor) < c) { const caught = nextRandom(randomValues, 65536, cursor) < y; return { numShakes: caught ? 4 : 0, criticalCapture: true, x, y, randomUsed: cursor.index }; } }
  let numShakes = 0; for (let i = 0; i < 4; i += 1) { if (numShakes < i) break; if (nextRandom(randomValues, 65536, cursor) < y) numShakes += 1; }
  return { numShakes, criticalCapture: false, x, y, randomUsed: cursor.index };
}
export function resolveCaptureFlow(input) {
  const operations = [];
  if (input.targetFainted) { operations.push({ op: "no_target" }); return { result: "no_target", numShakes: null, criticalCapture: false, decision: input.decision ?? 0, operations }; }
  if (input.trainerBattle && !(input.snagBall && input.shadowPokemon)) { operations.push({ op: "throw_and_deflect" }, { op: "trainer_block" }); return { result: "blocked", numShakes: null, criticalCapture: false, decision: input.decision ?? 0, operations }; }
  const capture = calculateCapture(input.capture); operations.push({ op: "throw", numShakes: capture.numShakes, criticalCapture: capture.criticalCapture });
  if (capture.numShakes !== 4) { operations.push({ op: "fail_catch", numShakes: capture.numShakes }); return { result: "failed", numShakes: capture.numShakes, criticalCapture: capture.criticalCapture, decision: input.decision ?? 0, firstPokeBall: input.pokeBallFailed ? (input.firstPokeBall ?? null) : input.ball, pokeBallFailed: true, operations, capture }; }
  operations.push({ op: "capture_success" }, { op: "remove_from_battle_party" }); if (input.gainExpForCapture) operations.push({ op: "set_captured", value: true }, { op: "gain_exp" }, { op: "set_captured", value: false }); operations.push({ op: "reset_battler" });
  let decision = input.decision ?? 0; if (input.allFaintedAfterCapture) decision = input.trainerBattle ? 1 : 4; if (input.snagBall) operations.push({ op: "transfer_owner_to_player" }); operations.push({ op: "on_catch" }, { op: "set_poke_ball", value: input.ball }); if (input.mega) operations.push({ op: "make_unmega" }); operations.push({ op: "make_unprimal" }); if (input.shadowPokemon) operations.push({ op: "update_shadow_moves" }); operations.push({ op: "record_first_moves" }); if (input.hasGetForm) operations.push({ op: "clear_forced_form" }); operations.push({ op: "on_leaving_battle", caught: true, usedInBattle: true }, { op: "hide_capture_ball" }, { op: "queue_caught_pokemon" });
  return { result: "caught", numShakes: 4, criticalCapture: capture.criticalCapture, decision, pokeBallFailed: Boolean(input.pokeBallFailed), firstPokeBall: input.firstPokeBall ?? null, operations, capture };
}

function clonePokemon(value) { if (value == null || typeof value !== "object") return value; return Array.isArray(value) ? value.map(clonePokemon) : Object.fromEntries(Object.entries(value).map(([k, v]) => [k, clonePokemon(v)])); }
function cloneState(input) { if (!input || typeof input !== "object") throw new TypeError("state is required"); const party = Array.isArray(input.party) ? input.party.map(clonePokemon) : []; const boxes = Array.isArray(input.boxes) ? input.boxes.map((box) => ({ ...box, slots: Array.isArray(box.slots) ? box.slots.map(clonePokemon) : [] })) : []; const currentBox = Number.isInteger(input.currentBox) ? input.currentBox : 0; return { ...input, party, boxes, currentBox }; }
function parseCapacity(value, fallback, field) { const parsed = value == null ? fallback : Number(value); if (!Number.isInteger(parsed) || parsed < 0) throw new TypeError(`${field} must be a non-negative integer`); return parsed; }
export function partyFull(state, maxPartySize = 6) { const value = cloneState(state); const limit = parseCapacity(maxPartySize, 6, "maxPartySize"); return value.party.length >= limit; }
function boxCapacity(box, fallbackCapacity) { return parseCapacity(box.capacity, fallbackCapacity, "box capacity"); }
function firstFreeBoxSlot(box, fallbackCapacity) { const capacity = boxCapacity(box, fallbackCapacity); for (let i = 0; i < capacity; i += 1) if (box.slots[i] == null) return i; return -1; }
export function boxesFull(state, defaultBoxCapacity = 30) { const value = cloneState(state); if (value.boxes.length === 0) return true; return value.boxes.every((box) => firstFreeBoxSlot(box, defaultBoxCapacity) < 0); }
export function storeCaughtInBoxes(state, pokemon, options = {}) { const value = cloneState(state); const defaultBoxCapacity = parseCapacity(options.defaultBoxCapacity, 30, "defaultBoxCapacity"); if (value.boxes.length === 0) return { state: value, storedBox: -1, storedSlot: -1, operations: [{ op: "boxes_full" }] }; const currentBox = value.currentBox >= 0 && value.currentBox < value.boxes.length ? value.currentBox : 0; const order = [currentBox, ...value.boxes.map((_, i) => i).filter((i) => i !== currentBox)]; const operations = []; if (options.healStoredPokemon && currentBox >= 0) operations.push({ op: "heal_before_storage" }); for (const boxIndex of order) { const slot = firstFreeBoxSlot(value.boxes[boxIndex], defaultBoxCapacity); if (slot < 0) continue; const slots = value.boxes[boxIndex].slots.slice(); while (slots.length <= slot) slots.push(null); slots[slot] = clonePokemon(pokemon); value.boxes[boxIndex] = { ...value.boxes[boxIndex], slots }; value.currentBox = boxIndex; operations.push({ op: "store_in_box", box: boxIndex, slot }); return { state: value, storedBox: boxIndex, storedSlot: slot, operations }; } operations.push({ op: "boxes_full" }); return { state: value, storedBox: -1, storedSlot: -1, operations }; }
export function storePokemonHandoff(state, pokemon, options = {}) { const value = cloneState(state); const maxPartySize = parseCapacity(options.maxPartySize, 6, "maxPartySize"); const defaultBoxCapacity = parseCapacity(options.defaultBoxCapacity, 30, "defaultBoxCapacity"); if (partyFull(value, maxPartySize) && boxesFull(value, defaultBoxCapacity)) return { result: "full", state: value, partyIndex: null, storedBox: -1, storedSlot: -1, operations: [{ op: "no_room" }] }; const operations = [{ op: "record_first_moves" }]; if (!partyFull(value, maxPartySize)) { value.party.push(clonePokemon(pokemon)); operations.push({ op: "add_to_party", index: value.party.length - 1 }); return { result: "party", state: value, partyIndex: value.party.length - 1, storedBox: null, storedSlot: null, operations }; } const stored = storeCaughtInBoxes(value, pokemon, options); operations.push(...stored.operations); if (stored.storedBox < 0) { operations.push({ op: "no_room" }); return { result: "full", state: stored.state, partyIndex: null, storedBox: -1, storedSlot: -1, operations }; } return { result: "box", state: stored.state, partyIndex: null, storedBox: stored.storedBox, storedSlot: stored.storedSlot, operations }; }
export function routeCaughtQueueToPartyStorage(state, caughtQueue, options = {}) { if (!Array.isArray(caughtQueue)) throw new TypeError("caughtQueue must be an array"); let currentState = state; const routed = []; const operations = [{ op: "receive_caught_queue", count: caughtQueue.length }]; for (let index = 0; index < caughtQueue.length; index += 1) { const result = storePokemonHandoff(currentState, caughtQueue[index], options); if (result.result === "full") { operations.push({ op: "route_blocked_full", index }); return { state: currentState, routed, remainingQueue: caughtQueue.slice(index), operations }; } currentState = result.state; routed.push({ index, result: result.result, partyIndex: result.partyIndex, storedBox: result.storedBox, storedSlot: result.storedSlot }); operations.push(...result.operations.filter((entry) => entry.op !== "record_first_moves"), { op: "consume_caught_queue_entry", index }); } operations.push({ op: "clear_caught_queue" }); return { state: currentState, routed, remainingQueue: [], operations }; }

function int(value, name) { const n = Number(value); if (!Number.isInteger(n)) throw new TypeError(`${name} must be an integer`); return n; }
export function quantity(slots, item) { let total = 0; for (const slot of slots) if (slot && slot[0] === item) total += slot[1]; return total; }
export function add(slots, maxSlots, maxPerSlot, item, qty) { qty = int(qty, "qty"); if (qty < 0) throw new RangeError("qty must be non-negative"); if (qty === 0) return true; for (let i = 0; i < maxSlots; i += 1) { const slot = slots[i]; if (!slot) { slots[i] = [item, Math.min(qty, maxPerSlot)]; qty -= slots[i][1]; if (qty === 0) return true; } else if (slot[0] === item && slot[1] < maxPerSlot) { const newAmount = Math.min(slot[1] + qty, maxPerSlot); qty -= newAmount - slot[1]; slot[1] = newAmount; if (qty === 0) return true; } } return false; }

function cloneValue(value) { if (value == null || typeof value !== "object") return value; return Array.isArray(value) ? value.map(cloneValue) : Object.fromEntries(Object.entries(value).map(([key, item]) => [key, cloneValue(item)])); }
function requireObject(value, field) { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError(`${field} must be an object`); return value; }
function valueIds(options = {}) { const ids = options.valueIds; if (!Array.isArray(ids) || ids.some((id) => typeof id !== "string" || id.length === 0)) throw new TypeError("valueIds must be an array of non-empty strings"); if (new Set(ids).size !== ids.length) throw new TypeError("valueIds must be unique"); return ids; }
export function compileSaveHash(runtimeState, options = {}) { const runtime = requireObject(runtimeState, "runtimeState"); const ids = valueIds(options); const saveData = {}; for (const id of ids) { if (!Object.hasOwn(runtime, id)) throw new TypeError(`missing registered save value: ${id}`); saveData[id] = cloneValue(runtime[id]); } return saveData; }
export function saveRunState(runtimeState, options = {}) { const saveData = compileSaveHash(runtimeState, options); return { payload: JSON.stringify(saveData), saveData, operations: [{ op: "compile_save_hash", valueIds: valueIds(options) }, { op: "write_portable_payload" }] }; }
export function readRunSave(payload) { if (typeof payload !== "string") throw new TypeError("payload must be a string"); const saveData = JSON.parse(payload); requireObject(saveData, "saveData"); return { saveData: cloneValue(saveData), operations: [{ op: "read_portable_payload" }] }; }
export function loadAllValues(saveData, runtimeState = {}, options = {}) { const save = requireObject(saveData, "saveData"); const runtime = cloneValue(requireObject(runtimeState, "runtimeState")); const ids = valueIds(options); const loadedIds = new Set(options.loadedIds ?? []); const defaults = options.defaults ?? {}; requireObject(defaults, "defaults"); const operations = []; for (const id of ids) { if (loadedIds.has(id)) { operations.push({ op: "skip_loaded", id }); continue; } if (Object.hasOwn(save, id)) { runtime[id] = cloneValue(save[id]); operations.push({ op: "load_value", id }); } else if (Object.hasOwn(defaults, id)) { runtime[id] = cloneValue(defaults[id]); operations.push({ op: "load_new_game_value", id }); } } return { state: runtime, operations }; }
export function loadRunState(payload, runtimeState = {}, options = {}) { const read = readRunSave(payload); const loaded = loadAllValues(read.saveData, runtimeState, options); return { state: loaded.state, saveData: read.saveData, operations: [...read.operations, ...loaded.operations] }; }
