const labels={pre_breakfast:'朝前',pre_lunch:'昼前',pre_dinner:'夕前',bedtime:'眠前'};
const doseLabels={breakfast_u:'朝',lunch_u:'昼',dinner_u:'夕',basal_u:'眠前 basal'};
const mealLabels={breakfast:'朝食',lunch:'昼食',dinner:'夕食'};
let DATA,state;
const $=s=>document.querySelector(s);
function rng(seed){let a=seed>>>0;return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function clamp(x,a,b){return Math.max(a,Math.min(b,x))}
fetch('data.json').then(r=>r.json()).then(d=>{DATA=d;startCase(Math.floor(Math.random()*d.cases.length))});
function startCase(i){const c=structuredClone(DATA.cases[i]),p=DATA.patients[c.patient_index];state={caseIndex:i,case:c,p,day:1,bg:{...c.previous_day_4point_bg_mg_dl},prevOrder:{...c.previous_order_u},prevIntake:{...c.intake_fraction},previousBasal:c.previous_order_u.basal_u,stableStreak:0,lastEnd:p.fasting_setpoint_mg_dl,seed:740000+i*1000,over:false,history:[]};render()}
function context(c){const b=[];b.push(`<span class="badge">eGFR ${Math.round(c.egfr_ml_min_1_73m2)}</span>`);if(c.infection_severity>0)b.push(`<span class="badge warn">感染 / ${c.fever_c.toFixed(1)}℃</span>`);if(c.steroid!=='none')b.push(`<span class="badge warn">PSL ${c.prednisolone_mg_am} mg 朝</span>`);if(b.length===1)b.push('<span class="badge">病態変化なし</span>');return b.join('')}
function mealClass(v){return v<=.5?'low':v<.9?'reduced':''}
function render(){const s=state,c=s.case;$('#dayNo').textContent=s.day;$('#caseId').textContent=c.case_id;$('#phenotype').textContent='1型糖尿病';$('#contextBadges').innerHTML=context(c);$('#bgGrid').innerHTML=Object.entries(s.bg).map(([k,v])=>`<div class="bg-card ${v<70?'low':v>180?'high':''}"><div class="bg-label">${labels[k]}</div><div class="bg-value">${Math.round(v)}</div><div class="bg-unit">mg/dL</div></div>`).join('');$('#mealGrid').innerHTML=Object.entries(s.prevIntake).map(([k,v])=>`<div class="meal-card ${mealClass(v)}"><div class="name">${mealLabels[k]}</div><div class="pct">${Math.round(v*10)}割</div></div>`).join('');$('#prevDoseGrid').innerHTML=Object.entries(s.prevOrder).map(([k,v])=>`<div class="prev-dose"><div class="name">${doseLabels[k]}</div><div class="value">${fmt(v)} U</div></div>`).join('');$('#doseGrid').innerHTML=Object.entries(s.prevOrder).map(([k,v])=>`<div class="dose-input-card"><label>${doseLabels[k]}</label><div class="input-wrap"><input inputmode="numeric" type="number" min="0" max="80" step="1" id="dose_${k}" value="${Math.round(v)}"><span class="unit-u">U</span></div></div>`).join('');$('#resultPanel').className='result-panel hidden';$('#submitBtn').disabled=false}
function fmt(x){return Number(x).toFixed(Number(x)%1?1:0)}
function readOrder(){const o={};for(const k of Object.keys(state.prevOrder)){let v=Number($('#dose_'+k).value);if(!Number.isFinite(v)||v<0)v=0;o[k]=Math.round(v)}return o}
function sampleIntake(){const r=rng(state.seed+state.day*7919+71),out={};for(const k of ['breakfast','lunch','dinner']){const base=state.case.intake_fraction[k]??1;if(base>=.95){const u=r();out[k]=u<.68?1:u<.83?.9:u<.93?.8:u<.98?.7:.6}else{const shift=Math.round((r()-.5)*4)/10;out[k]=clamp(Math.round((base+shift)*10)/10,.2,1)}}return out}
function intakeText(x){return `朝 ${Math.round(x.breakfast*10)}割 / 昼 ${Math.round(x.lunch*10)}割 / 夕 ${Math.round(x.dinner*10)}割`}
function dailyFeedbackHtml(rec){const pts=[];const prev=rec.previousBg,next=rec.result.bg,o0=rec.previousOrder,o1=rec.order;const pairs=[['breakfast_u','pre_lunch','朝rapid','昼前'],['lunch_u','pre_dinner','昼rapid','夕前'],['dinner_u','bedtime','夕rapid','眠前']];for(const [dk,bk,dn,bn] of pairs){const dd=o1[dk]-o0[dk],db=next[bk]-prev[bk];if(Math.abs(dd)>=1){if(dd>0&&db< -10)pts.push(`${dn}を${dd>0?'+':''}${dd} U変更し、${bn}は前日より${Math.round(Math.abs(db))} mg/dL低下しました。`);else if(dd<0&&db>10)pts.push(`${dn}を${dd} U変更し、${bn}は前日より${Math.round(db)} mg/dL上昇しました。`);else pts.push(`${dn}を${dd>0?'+':''}${dd} U変更しました。${bn}は${Math.round(next[bk])} mg/dLでした。`)}}
const lowest=Object.entries(rec.intake).sort((a,b)=>a[1]-b[1])[0];if(lowest[1]<=.7)pts.push(`${mealLabels[lowest[0]]}は${Math.round(lowest[1]*10)}割摂取でした。食事量低下は低血糖方向に働きます。`);if(state.case.prednisolone_mg_am>0&&next.pre_dinner>180)pts.push(`朝PSL ${state.case.prednisolone_mg_am} mg設定では、午後〜夜の高血糖が残りやすい症例です。`);if(state.case.infection_severity>0&&Math.max(...Object.values(next))>180)pts.push('感染設定によるインスリン抵抗性が高血糖方向に働いています。');if(state.case.egfr_ml_min_1_73m2<45&&Math.min(...Object.values(next))<100)pts.push('腎機能低下設定があり、低血糖側への余裕は小さめです。');if(!pts.length){const vals=Object.values(next);if(vals.every(x=>x>=100&&x<=180))pts.push('4検はすべて100–180 mg/dL内です。この日の処方は安定方向でした。');else pts.push('危険域は回避しています。次の4検のどこが高い/低いかを見て、対応するインスリンを考えてください。')}
return `<div class="feedback-box"><div class="feedback-title">この日の振り返り</div><ul class="feedback-list">${pts.slice(0,3).map(x=>`<li>${x}</li>`).join('')}</ul></div>`}
function feedbackHtml(kind,rec){const pts=[];const c=state.case;const lowMeal=Object.entries(rec.intake).sort((a,b)=>a[1]-b[1])[0];if(kind==='low'){pts.push(`このゲーム内では最低血糖が ${Math.round(rec.result.min)} mg/dL まで低下しました。`);if(lowMeal[1]<=.6)pts.push(`${mealLabels[lowMeal[0]]}は${Math.round(lowMeal[1]*10)}割摂取で、食事量低下が低血糖方向の要因になりました。`);if(c.egfr_ml_min_1_73m2<45)pts.push('この症例は腎機能低下設定があり、インスリン作用が強まりやすい条件でした。')}else if(kind==='high'){pts.push(`このゲーム内では最高血糖が ${Math.round(rec.result.max)} mg/dL まで上昇しました。`);if(c.prednisolone_mg_am>0)pts.push(`朝PSL ${c.prednisolone_mg_am} mg設定により、午後〜夜のインスリン感受性が低下する症例でした。`);if(c.infection_severity>0)pts.push('感染設定によるインスリン抵抗性上昇も高血糖方向に作用しました。')}else{pts.push('3日連続で4検100–180 mg/dLかつ処方変更が各±1 U以内となり、安定軌道判定に入りました。');const first=state.history[0]?.order,last=rec.order;if(first&&last){const keys=Object.keys(last),k=keys.sort((a,b)=>Math.abs(last[b]-first[b])-Math.abs(last[a]-first[a]))[0];const d=last[k]-first[k];if(Math.abs(d)>=1)pts.push(`今回もっとも大きく調整したのは${doseLabels[k]}で、開始時から${d>0?'+':''}${d} Uでした。`)}}
pts.push('フィードバックはこのシミュレータ内の因果関係に基づく振り返りで、実患者への投与推奨ではありません。');return `<div class="feedback-box"><div class="feedback-title">振り返り</div><ul class="feedback-list">${pts.map(x=>`<li>${x}</li>`).join('')}</ul></div>`}
$('#newCaseBtn').onclick=()=>startCase((state.caseIndex+1+Math.floor(Math.random()*(DATA.cases.length-1)))%DATA.cases.length);
$('#submitBtn').onclick=()=>{if(state.over)return;const o=readOrder(),intake=sampleIntake(),ctx={...state.case,intake_fraction:intake},rapid={breakfast_u:o.breakfast_u,lunch_u:o.lunch_u,dinner_u:o.dinner_u};const r=GlucoseEngine.simulate(state.p,ctx,rapid,state.previousBasal,state.seed+state.day,state.lastEnd);const fatalLow=r.min<70,fatalHigh=r.max>400;const allTarget=Object.values(r.bg).every(x=>x>=100&&x<=180);const doseCalm=Object.keys(o).every(k=>Math.abs(o[k]-state.prevOrder[k])<=1);state.stableStreak=(allTarget&&doseCalm)?state.stableStreak+1:0;const rec={day:state.day,previousBg:{...state.bg},previousOrder:{...state.prevOrder},order:{...o},intake:{...intake},result:r};state.history.push(rec);state.bg=r.bg;state.lastEnd=r.end;state.previousBasal=o.basal_u;state.prevOrder=o;state.prevIntake=intake;const panel=$('#resultPanel');panel.className='result-panel '+((fatalLow||fatalHigh)?'fail':'ok');let title,text,terminal=false,kind='';if(fatalLow){title='低血糖で終了';text=`日中の血糖が ${Math.round(r.min)} mg/dL まで低下しました。`;terminal=true;kind='low'}else if(fatalHigh){title='400超で終了';text=`日中の血糖が ${Math.round(r.max)} mg/dL まで上昇しました。`;terminal=true;kind='high'}else if(state.stableStreak>=3){title='安定軌道に到達';text='3日連続で4検が安定し、処方変更も小さくなりました。クリアです。';terminal=true;kind='clear'}else{title='翌日の4検';text=`朝前 ${Math.round(r.bg.pre_breakfast)} / 昼前 ${Math.round(r.bg.pre_lunch)} / 夕前 ${Math.round(r.bg.pre_dinner)} / 眠前 ${Math.round(r.bg.bedtime)} mg/dL`;}
const mealLine=`<div class="result-text" style="margin-top:7px">本日の実摂取：${intakeText(intake)}</div>`;const fb=terminal?feedbackHtml(kind,rec):dailyFeedbackHtml(rec);panel.innerHTML=`<div class="result-kicker">${terminal?'RESULT':'DAY '+state.day}</div><div class="result-title">${title}</div><div class="result-text">${text}</div>${mealLine}${fb}${terminal?'<button class="next-btn" id="restartBtn">新しい患者へ</button>':'<button class="next-btn" id="nextDayBtn">次の日へ</button>'}`;panel.scrollIntoView({behavior:'smooth',block:'nearest'});if(terminal){state.over=true;$('#submitBtn').disabled=true;$('#restartBtn').onclick=()=>startCase(Math.floor(Math.random()*DATA.cases.length))}else{$('#submitBtn').disabled=true;$('#nextDayBtn').onclick=()=>{state.day++;render();window.scrollTo({top:0,behavior:'smooth'})}}};
