const labels={pre_breakfast:'朝前',pre_lunch:'昼前',pre_dinner:'夕前',bedtime:'眠前'};
const doseLabels={breakfast_u:'朝',lunch_u:'昼',dinner_u:'夕',basal_u:'眠前 basal'};
let DATA,state;
const $=s=>document.querySelector(s);
fetch('data.json').then(r=>r.json()).then(d=>{DATA=d;startCase(Math.floor(Math.random()*d.cases.length))});
function startCase(i){const c=structuredClone(DATA.cases[i]),p=DATA.patients[c.patient_index];state={caseIndex:i,case:c,p,day:1,bg:{...c.previous_day_4point_bg_mg_dl},prevOrder:{...c.previous_order_u},previousBasal:c.previous_order_u.basal_u,stableStreak:0,lastEnd:p.fasting_setpoint_mg_dl,seed:740000+i*1000,over:false};render()}
function context(c){const b=[];b.push(`<span class="badge">eGFR ${Math.round(c.egfr_ml_min_1_73m2)}</span>`);if(c.infection_severity>0)b.push(`<span class="badge warn">感染 / ${c.fever_c.toFixed(1)}℃</span>`);if(c.steroid!=='none')b.push(`<span class="badge warn">PSL ${c.prednisolone_mg_am} mg 朝</span>`);for(const [k,v] of Object.entries(c.intake_fraction))if(v<.99)b.push(`<span class="badge danger">${k==='breakfast'?'朝':k==='lunch'?'昼':'夕'}食 ${Math.round(v*100)}%</span>`);if(b.length===1)b.push('<span class="badge">全量摂取</span>');return b.join('')}
function render(){const s=state,c=s.case;$('#dayNo').textContent=s.day;$('#caseId').textContent=c.case_id;$('#phenotype').textContent='1型糖尿病';$('#contextBadges').innerHTML=context(c);$('#bgGrid').innerHTML=Object.entries(s.bg).map(([k,v])=>`<div class="bg-card ${v<70?'low':v>180?'high':''}"><div class="bg-label">${labels[k]}</div><div class="bg-value">${Math.round(v)}</div><div class="bg-unit">mg/dL</div></div>`).join('');$('#prevDoseGrid').innerHTML=Object.entries(s.prevOrder).map(([k,v])=>`<div class="prev-dose"><div class="name">${doseLabels[k]}</div><div class="value">${fmt(v)} U</div></div>`).join('');$('#doseGrid').innerHTML=Object.entries(s.prevOrder).map(([k,v])=>`<div class="dose-input-card"><label>${doseLabels[k]}</label><div class="input-wrap"><input inputmode="decimal" type="number" min="0" max="80" step="0.5" id="dose_${k}" value="${fmt(v)}"><span class="unit-u">U</span></div></div>`).join('');$('#resultPanel').className='result-panel hidden';$('#submitBtn').disabled=false}
function fmt(x){return Number(x).toFixed(Number(x)%1?1:0)}
function readOrder(){const o={};for(const k of Object.keys(state.prevOrder)){let v=Number($('#dose_'+k).value);if(!Number.isFinite(v)||v<0)v=0;o[k]=Math.round(v*2)/2}return o}
$('#newCaseBtn').onclick=()=>startCase((state.caseIndex+1+Math.floor(Math.random()*(DATA.cases.length-1)))%DATA.cases.length);
$('#submitBtn').onclick=()=>{if(state.over)return;const o=readOrder(),rapid={breakfast_u:o.breakfast_u,lunch_u:o.lunch_u,dinner_u:o.dinner_u};const r=GlucoseEngine.simulate(state.p,state.case,rapid,state.previousBasal,state.seed+state.day,state.lastEnd);const fatalLow=r.min<70,fatalHigh=r.max>400;const allTarget=Object.values(r.bg).every(x=>x>=100&&x<=180);const doseCalm=Object.keys(o).every(k=>Math.abs(o[k]-state.prevOrder[k])<=1);state.stableStreak=(allTarget&&doseCalm)?state.stableStreak+1:0;state.bg=r.bg;state.lastEnd=r.end;state.previousBasal=o.basal_u;state.prevOrder=o;const panel=$('#resultPanel');panel.className='result-panel '+((fatalLow||fatalHigh)?'fail':'ok');let title,text,terminal=false;if(fatalLow){title='低血糖で終了';text=`日中の血糖が ${Math.round(r.min)} mg/dL まで低下しました。`;terminal=true}else if(fatalHigh){title='400超で終了';text=`日中の血糖が ${Math.round(r.max)} mg/dL まで上昇しました。`;terminal=true}else if(state.stableStreak>=3){title='安定軌道に到達';text='3日連続で4検が安定し、処方変更も小さくなりました。クリアです。';terminal=true}else{title='翌日の4検';text=`朝前 ${Math.round(r.bg.pre_breakfast)} / 昼前 ${Math.round(r.bg.pre_lunch)} / 夕前 ${Math.round(r.bg.pre_dinner)} / 眠前 ${Math.round(r.bg.bedtime)} mg/dL`;}
panel.innerHTML=`<div class="result-kicker">${terminal?'RESULT':'DAY '+state.day}</div><div class="result-title">${title}</div><div class="result-text">${text}</div>${terminal?'<button class="next-btn" id="restartBtn">新しい患者へ</button>':'<button class="next-btn" id="nextDayBtn">次の日へ</button>'}`;panel.scrollIntoView({behavior:'smooth',block:'nearest'});if(terminal){state.over=true;$('#submitBtn').disabled=true;$('#restartBtn').onclick=()=>startCase(Math.floor(Math.random()*DATA.cases.length))}else{$('#submitBtn').disabled=true;$('#nextDayBtn').onclick=()=>{state.day++;render();window.scrollTo({top:0,behavior:'smooth'})}}};
