const labels={pre_breakfast:'朝前',pre_lunch:'昼前',pre_dinner:'夕前',bedtime:'眠前'};
const doseLabels={breakfast_u:'朝',lunch_u:'昼',dinner_u:'夕',basal_u:'眠前 basal'};
const mealLabels={breakfast:'朝食',lunch:'昼食',dinner:'夕食'};
let state,runCounter=0;
const $=s=>document.querySelector(s);
function rng(seed){let a=seed>>>0;return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function clamp(x,a,b){return Math.max(a,Math.min(b,x))}
function newSeed(){runCounter++;let x=(Date.now()^(runCounter*2654435761))>>>0;try{const a=new Uint32Array(1);crypto.getRandomValues(a);x^=a[0]}catch{}return x>>>0}
function startGenerated(seed=newSeed()){let bundle;try{bundle=PatientGenerator.generate(seed)}catch(e){console.error(e);bundle=PatientGenerator.generate((seed+0x9E3779B9)>>>0)}const c=bundle.case,p=bundle.patient;state={seed,case:c,p,day:1,bg:{...c.previous_day_4point_bg_mg_dl},prevOrder:{...c.previous_order_u},prevIntake:{...c.intake_fraction},previousBasal:c.previous_order_u.basal_u,stableStreak:0,lastEnd:p.fasting_setpoint_mg_dl,over:false,history:[],generatorAttempts:bundle.attempts};render()}
function context(c){const b=[];b.push(`<span class="badge">eGFR ${Math.round(c.egfr_ml_min_1_73m2)}</span>`);if(c.infection_severity>0)b.push(`<span class="badge warn">感染 / ${c.fever_c.toFixed(1)}℃</span>`);if(b.length===1)b.push('<span class="badge">病態変化なし</span>');return b.join('')}
function mealClass(v){return v<=.5?'low':v<.9?'reduced':''}
function ensureHistoryPanel(){if($('#runHistory'))return;const result=$('#resultPanel');if(!result)return;const sec=document.createElement('section');sec.id='runHistory';sec.className='section-block';sec.style.marginTop='24px';sec.innerHTML='<div class="section-title"><span>H</span> この患者の経過</div><div id="runHistoryBody"></div>';result.parentNode.insertBefore(sec,result)}
function bgClass(v){return v<70?'color:#c53a3a':v>180?'color:#b86b15':''}
function historyCell(label,value,sub='',style=''){return `<div style="min-width:0;text-align:center;padding:8px 4px"><div style="font-size:9px;color:#8b919a;margin-bottom:3px">${label}</div><div style="font-size:15px;font-weight:760;${style}">${value}</div>${sub?`<div style="font-size:8px;color:#a0a5ad;margin-top:1px">${sub}</div>`:''}</div>`}
function renderHistory(){ensureHistoryPanel();const body=$('#runHistoryBody');if(!body)return;if(!state.history.length){body.innerHTML='<div style="font-size:11px;color:#8b919a;padding:2px 0 4px">まだあなたの処方記録はありません。</div>';return}body.innerHTML=state.history.map(rec=>{const o=rec.order,i=rec.intake,b=rec.result.bg;return `<div style="background:#fff;border:1px solid #e6e8ed;border-radius:17px;padding:12px;margin-bottom:10px;box-shadow:0 5px 18px rgba(25,30,40,.035)"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:7px"><div style="font-size:11px;font-weight:800;letter-spacing:.06em">DAY ${rec.day}</div><div style="font-size:9px;color:#8b919a">あなたの処方 → 実摂取 → 結果</div></div><div style="font-size:9px;font-weight:750;color:#6c727c;margin:5px 0 2px">処方</div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:2px;background:#f6f7f9;border-radius:11px">${historyCell('朝',fmt(o.breakfast_u),'U')}${historyCell('昼',fmt(o.lunch_u),'U')}${historyCell('夕',fmt(o.dinner_u),'U')}${historyCell('眠前',fmt(o.basal_u),'U basal')}</div><div style="font-size:9px;font-weight:750;color:#6c727c;margin:9px 0 2px">実摂取</div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:2px;background:#f6f7f9;border-radius:11px">${historyCell('朝食',Math.round(i.breakfast*10)+'割')}${historyCell('昼食',Math.round(i.lunch*10)+'割')}${historyCell('夕食',Math.round(i.dinner*10)+'割')}</div><div style="font-size:9px;font-weight:750;color:#6c727c;margin:9px 0 2px">翌4検</div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:2px;background:#f6f7f9;border-radius:11px">${historyCell('朝前',Math.round(b.pre_breakfast),'mg/dL',bgClass(b.pre_breakfast))}${historyCell('昼前',Math.round(b.pre_lunch),'mg/dL',bgClass(b.pre_lunch))}${historyCell('夕前',Math.round(b.pre_dinner),'mg/dL',bgClass(b.pre_dinner))}${historyCell('眠前',Math.round(b.bedtime),'mg/dL',bgClass(b.bedtime))}</div></div>`}).join('')}
function render(){const s=state,c=s.case;$('#dayNo').textContent=s.day;$('#caseId').textContent=c.case_id;$('#phenotype').textContent='1型糖尿病';$('#contextBadges').innerHTML=context(c);$('#bgGrid').innerHTML=Object.entries(s.bg).map(([k,v])=>`<div class="bg-card ${v<70?'low':v>180?'high':''}"><div class="bg-label">${labels[k]}</div><div class="bg-value">${Math.round(v)}</div><div class="bg-unit">mg/dL</div></div>`).join('');$('#mealGrid').innerHTML=Object.entries(s.prevIntake).map(([k,v])=>`<div class="meal-card ${mealClass(v)}"><div class="name">${mealLabels[k]}</div><div class="pct">${Math.round(v*10)}割</div></div>`).join('');$('#prevDoseGrid').innerHTML=Object.entries(s.prevOrder).map(([k,v])=>`<div class="prev-dose"><div class="name">${doseLabels[k]}</div><div class="value">${fmt(v)} U</div></div>`).join('');$('#doseGrid').innerHTML=Object.entries(s.prevOrder).map(([k,v])=>`<div class="dose-input-card"><label>${doseLabels[k]}</label><div class="input-wrap"><input inputmode="numeric" type="number" min="0" max="80" step="1" id="dose_${k}" value="${Math.round(v)}"><span class="unit-u">U</span></div></div>`).join('');$('#resultPanel').className='result-panel hidden';$('#submitBtn').disabled=false;renderHistory()}
function fmt(x){return Number(x).toFixed(Number(x)%1?1:0)}
function readOrder(){const o={};for(const k of Object.keys(state.prevOrder)){let v=Number($('#dose_'+k).value);if(!Number.isFinite(v)||v<0)v=0;o[k]=Math.round(v)}return o}
function sampleIntake(){const r=rng((state.seed+state.day*7919+71)>>>0),out={};for(const k of ['breakfast','lunch','dinner']){const base=state.case.intake_fraction[k]??1;if(base>=.95){const u=r();out[k]=u<.68?1:u<.83?.9:u<.93?.8:u<.98?.7:.6}else{const shift=Math.round((r()-.5)*4)/10;out[k]=clamp(Math.round((base+shift)*10)/10,.2,1)}}return out}
function intakeText(x){return `朝 ${Math.round(x.breakfast*10)}割 / 昼 ${Math.round(x.lunch*10)}割 / 夕 ${Math.round(x.dinner*10)}割`}
function gameOverFeedback(kind,rec){const pts=[];const c=state.case;const lowMeal=Object.entries(rec.intake).sort((a,b)=>a[1]-b[1])[0];if(kind==='low'){pts.push(`最低血糖は ${Math.round(rec.result.min)} mg/dL でした。`);if(lowMeal[1]<=.6)pts.push(`${mealLabels[lowMeal[0]]}が${Math.round(lowMeal[1]*10)}割摂取まで低下しており、食事量低下が低血糖方向に作用しました。`);if(c.egfr_ml_min_1_73m2<45)pts.push('腎機能低下設定があり、インスリン作用が強まりやすい症例でした。');const d=rec.order;const matched={breakfast_u:50/state.p.icr_g_u,lunch_u:70/state.p.icr_g_u,dinner_u:60/state.p.icr_g_u};for(const k of ['breakfast_u','lunch_u','dinner_u'])if(d[k]>matched[k]+2)pts.push(`${doseLabels[k]}rapidはこの患者の基準量よりかなり多い設定でした。`)}else{pts.push(`最高血糖は ${Math.round(rec.result.max)} mg/dL でした。`);if(c.infection_severity>0)pts.push('感染設定によるインスリン抵抗性上昇が高血糖方向に作用しました。');const d=rec.order,matched={breakfast_u:50/state.p.icr_g_u,lunch_u:70/state.p.icr_g_u,dinner_u:60/state.p.icr_g_u};for(const k of ['breakfast_u','lunch_u','dinner_u'])if(d[k]<Math.max(0,matched[k]-2))pts.push(`${doseLabels[k]}rapidはこの患者の基準量よりかなり少ない設定でした。`)}pts.push('これはシミュレータ内部の因果関係に基づく振り返りで、実患者への投与推奨ではありません。');return `<div class="feedback-box"><div class="feedback-title">ゲームオーバー振り返り</div><ul class="feedback-list">${pts.slice(0,4).map(x=>`<li>${x}</li>`).join('')}</ul></div>`}
$('#newCaseBtn').onclick=()=>startGenerated();
$('#submitBtn').onclick=()=>{if(state.over)return;const o=readOrder(),intake=sampleIntake(),ctx={...state.case,intake_fraction:intake},rapid={breakfast_u:o.breakfast_u,lunch_u:o.lunch_u,dinner_u:o.dinner_u};const r=GlucoseEngine.simulate(state.p,ctx,rapid,state.previousBasal,(state.seed+state.day)>>>0,state.lastEnd);const fatalLow=r.min<70,fatalHigh=r.max>400;const allTarget=Object.values(r.bg).every(x=>x>=100&&x<=180);const doseCalm=Object.keys(o).every(k=>Math.abs(o[k]-state.prevOrder[k])<=1);state.stableStreak=(allTarget&&doseCalm)?state.stableStreak+1:0;const rec={day:state.day,previousBg:{...state.bg},previousOrder:{...state.prevOrder},order:{...o},intake:{...intake},result:r};state.history.push(rec);state.bg=r.bg;state.lastEnd=r.end;state.previousBasal=o.basal_u;state.prevOrder=o;state.prevIntake=intake;renderHistory();const panel=$('#resultPanel');panel.className='result-panel '+((fatalLow||fatalHigh)?'fail':'ok');let title,text,terminal=false,kind='';if(fatalLow){title='低血糖で終了';text=`日中の血糖が ${Math.round(r.min)} mg/dL まで低下しました。`;terminal=true;kind='low'}else if(fatalHigh){title='400超で終了';text=`日中の血糖が ${Math.round(r.max)} mg/dL まで上昇しました。`;terminal=true;kind='high'}else if(state.stableStreak>=3){title='安定軌道に到達';text='3日連続で4検が安定し、処方変更も小さくなりました。クリアです。';terminal=true}else{title='翌日の4検';text=`朝前 ${Math.round(r.bg.pre_breakfast)} / 昼前 ${Math.round(r.bg.pre_lunch)} / 夕前 ${Math.round(r.bg.pre_dinner)} / 眠前 ${Math.round(r.bg.bedtime)} mg/dL`}
const mealLine=`<div class="result-text" style="margin-top:7px">本日の実摂取：${intakeText(intake)}</div>`;const fb=(fatalLow||fatalHigh)?gameOverFeedback(kind,rec):'';panel.innerHTML=`<div class="result-kicker">${terminal?'RESULT':'DAY '+state.day}</div><div class="result-title">${title}</div><div class="result-text">${text}</div>${mealLine}${fb}${terminal?'<button class="next-btn" id="restartBtn">新しい患者へ</button>':'<button class="next-btn" id="nextDayBtn">次の日へ</button>'}`;panel.scrollIntoView({behavior:'smooth',block:'nearest'});if(terminal){state.over=true;$('#submitBtn').disabled=true;$('#restartBtn').onclick=()=>startGenerated()}else{$('#submitBtn').disabled=true;$('#nextDayBtn').onclick=()=>{state.day++;render();window.scrollTo({top:0,behavior:'smooth'})}}};
startGenerated();
